### ISSUE TITLE
The problem happend, when I used render.py

### ISSUE THREAD

**Issue by lingtengqiu** [facebookresearch/InterHand2.6M#21]
Could u help me to address this problem.
```
Traceback (most recent call last):
  File "/home/adminroot/myproject/py_3_6_benchmark/lib/python3.6/site-packages/pyrender/platforms/pyglet_platform.py", line 39, in init_context
    width=1, height=1)
  File "/home/adminroot/myproject/py_3_6_benchmark/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 173, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/adminroot/myproject/py_3_6_benchmark/lib/python3.6/site-packages/pyglet/window/__init__.py", line 603, in __init__
    config = screen.get_best_config(config)
  File "/home/adminroot/myproject/py_3_6_benchmark/lib/python3.6/site-packages/pyglet/canvas/base.py", line 194, in get_best_config
    raise window.NoSuchConfigException()
pyglet.window.NoSuchConfigException
```

**Comment by mks0601** [comment]
I think you ran the code in ssh environment? For the rendering, you should use a machine with available display device. Or you can search google to fix this issue.
